<?php

declare(strict_types=1);

namespace Midnite81\Core\Attributes;

use Attribute;

/**
 * The IgnoreProperty attribute marks a class property to be excluded from serialization processes,
 * such as when converting an object to an array or JSON format. This attribute is particularly
 * useful in classes that inherit from BaseEntity or similar base classes equipped with mechanisms
 * for automatic property serialization.
 *
 * Applying this attribute to a property signals the serialization logic within BaseEntity (or similar)
 * to omit the property from the output, thereby not including it in the serialized data structure
 * (arrays, JSON, etc.). This can be useful for hiding sensitive information or avoiding the serialization
 * of properties that are not relevant to the consumer of the serialized data.
 *
 * Example usage within a class extending BaseEntity:
 * #[IgnoreProperty]
 * private $sensitiveInformation;
 *
 * In this example, the `sensitiveInformation` property will be excluded from any serialized outputs
 * generated by methods of the BaseEntity or a similar base class, such as toArray() or toJson().
 * This approach ensures that certain properties can be kept private and not inadvertently exposed
 * through serialization.
 *
 * Note: The effectiveness of this attribute relies on its support within the serialization logic of
 * BaseEntity or the base class handling serialization. It is essential to integrate this attribute's
 * functionality into the base class's serialization methods to achieve the desired effect.
 *
 * @Annotation
 *
 * @Target({"PROPERTY"})
 */
#[Attribute(Attribute::TARGET_PROPERTY)]
class IgnoreProperty
{
    public function __construct()
    {
    }
}
